### ISSUE TITLE
Implement database on EC2 instance

### ISSUE THREAD

**Issue by sebastianquek** [threemoji/threemoji#3]
Database needs to contain the following tables and columns:
_Users_ : 3 Emoji, Generated name, GCM authorisation ID (aka token)

> The 3 Emoji and generated name will be used as a way for the client to find the correct token of the recipient. When the token is modified, the server needs to update all rows with that token.

**Comment by whipermr5** [comment]
Implemented database on Google Cloud Datastore. For each user, an entity of kind "User" is created, with the following fields: name (a UUID randomly generated by the client; also the key), date_created, date_modified, emoji_1, emoji_2, emoji_3, gender, generated_name, location, password, radius and token.
